### ISSUE TITLE
May I ask why the behavior is not quite as expected?

### ISSUE THREAD

**Issue by ityuany** [dai-shi/proxy-compare#65]
I think maybe my understanding of proxy-compare is not deep enough. I encountered a phenomenon that I couldn't understand while using it, and I hope to get your answer.

Thank you very much.

```ts
import { isChanged, createProxy } from 'proxy-compare';
const data = {
  td: {
    brandId: 1,
    tkRepositoryIds: 2,
  },
};
const affected = new WeakMap();
const p = createProxy(data, affected);
p.td.brandId;
p.td;
console.log(affected);

const res = isChanged(
  data,
  {
    td: {
      brandId: 1,
      tkRepositoryIds: 4,
    },
  },
  affected,
  new WeakMap()
);

//  I think his result should be true, but the actual result is false. I don't quite understand.
console.log(res);

```

**Comment by dai-shi** [comment]
Well, it's how it's designed. (Or, it can be said, it's the limitation with runtime solution.)

```js
p.td.brandId;
p.td;
```
We treat it ☝️  the same as 👇 
```js
p.td;
p.td.brandId;
```
which is equivalent to 👇 
```js
p.td.brandId;
```

(We might be able to detect the access order to overcome this, but it would be less predictable, so the current behavior is our design decision.)

**Comment by ityuany** [comment]
I can't understand why there is an additional access to `p.td`, and the result has such a big difference. My understanding is that `td` should also have different memory addresses, theoretically it should be false.


```ts
import { isChanged, createProxy } from 'proxy-compare';
const data = {
  td: {
    brandId: 1,
    tkRepositoryIds: 2,
  },
};
const affected = new WeakMap();
const p = createProxy(data, affected);
p.td.brandId;
p.td;
console.log(affected);

const res = isChanged(
  data,
  {
    td: {
      brandId: 1,
      tkRepositoryIds: 4,
    },
  },
  affected,
  new WeakMap()
);

//   false
console.log(res);

```




```ts
import { isChanged, createProxy } from 'proxy-compare';
const data = {
  td: {
    brandId: 1,
    tkRepositoryIds: 2,
  },
};
const affected = new WeakMap();
const p = createProxy(data, affected);
p.td.brandId;
console.log(affected);

const res = isChanged(
  data,
  {
    td: {
      brandId: 1,
      tkRepositoryIds: 4,
    },
  },
  affected,
  new WeakMap()
);

//   true
console.log(res);

```

**Comment by ityuany** [comment]
我发现一个有趣的现象

```ts
import { isChanged, createProxy } from 'proxy-compare';
const data = {
  td: {
    brandId: 1,
    tkRepositoryIds: 2,
  },
};
const affected = new WeakMap();
const p = createProxy(data, affected);
// p.td.brandId;
p.td;

const res = isChanged(
  data,
  {
    td: {
      brandId: 1,
      tkRepositoryIds: 4,
    },
  },
  affected,
  new WeakMap()
);

// true
console.log(res);
```

**Comment by ityuany** [comment]
总结一下，

- 单独访问  `p.td.brandId`  返回 `false` , 这是符合预期的 因为 brandId 并没有发生变化
- 单独访问 `p.td` 返回 `true` ， 这也是符合预期的 ， 因为两个td 的对象引用地址不同
- 同时访问  `p.td.brandId` 、 `p.td` ，返回 `false` ， 这不太符合预期， 虽然 `brandId` 没有发生变化， 但是 `td` 并不相等，  我的预期是 他应该返回 `false` 

我发现 affected 中实际上记录了  `brandId` 和 `td` , 也就是说应当同时比较  `brandId` 和 `td`  ， 不是很理解 为什么 

```ts
p.td;
p.td.brandId;
```

which is equivalent to 👇

```ts
p.td.brandId;
```

**Comment by dai-shi** [comment]
What would be your expectation of the behavior of this?
```js
const x = p.td;
x.brandId;
```

**Comment by ityuany** [comment]
> What would be your expectation of the behavior of this?
> 
> ```js
> const x = p.td;
> x.brandId;
> ```

The expected behavior, as I understand it, is to track `td` and `brandId`. When either `td` or `brandId` changes to any value, `isChange` should return `false`.

**Comment by dai-shi** [comment]
```js
const x = p.td;
x.brandId;
```
We can't distinguish that ☝️ from this 👇 .
```js
p.td;
p.td.brandId;
```

---

For valtio, we consider it a limitation.
https://github.com/pmndrs/valtio/blob/d1e462e14fe1d0a161c5514718ce10c1980c35ba/docs/how-tos/some-gotchas.mdx#L51
https://github.com/pmndrs/valtio/blob/d1e462e14fe1d0a161c5514718ce10c1980c35ba/docs/how-tos/some-gotchas.mdx#L135

**Comment by ityuany** [comment]
ok , thanks .
