### ISSUE TITLE
Optimizing isChanged -- CHANGED_PROPERTY + changed === null can be removed

### ISSUE THREAD

**Issue by faceyspacey** [dai-shi/proxy-compare#76]
I think `isChanged` doesn't need to cache whether each object reference was `changed`, just the the reference itself. 

Instead we can simply short-circuit by returning `false` if the reference was found:

```js
const hit = cache.get(prevObj)
if (hit === next) return false

cache.set(prevObj, nextObj) // cache just the nextObj, no need to cache CHANGED_PROPERTY bool
```

currently it looks like this:

```js
const hit = cache.get(prevObj)
if (hit && hit[NEXT_OBJECT_PROPERTY] === nextObj) return hit[NEXT_OBJECT_PROPERTY]

cache.set(prevObj, {
  [NEXT_OBJECT_PROPERTY]: nextObj,
  [CHANGED_PROPERTY]: false,
})
```

Logically, `hit[CHANGED_PROPERTY]` will never be any other value than `false` given the recursion short-circuits and returns to the top the moment a *change* has occurred (and given `cache.get(prevObj)` is already called breadth-first).

The `cache` is recreated for each recursion. Therefore, we aren't concerning ourselves with cache hits in future recursions. All we care about is whether `isChanged` is true or not in this single recursion. The moment it's true, nothing else happens, the recursion is over and returns to the top.

So the cache will never be hit in this case -- again because it's *first* checked breadth first while we jump from tail depth to top the moment we receive `true`.

In fact, the cache will primarily be hit outside of cycles when there are siblings containing the same ref (or sibling branches that contain the same ref). In this case, the cache acts as an optimization to ensure the recursion of the given ref doesn't happen again just to come to the same result of `false`. 

Therefore I also propose to remove the `finally` clause, as we already have our answer by the mere presence of the same object reference. And again, that *answer* is always `false`. We never need to set it to true:

```js
finally {
  cache.set(prevObj, {
    [NEXT_OBJECT_PROPERTY]: nextObj,
    [CHANGED_PROPERTY]: true, // THIS NEVER HAPPENS
})
```

In addition, we can get also remove `changed === null` as it's **unreachable**, as `changed` will never be `null` if there were any `used` keys, as at least one of them will always have assigned to `changed`. 

All we need is the initial check of whether anything was `used`:

```js
const used = affected.get(prevObj)
if (!used) return true
``` 

To support component-level memoization or `!!snap.obj`, this ideally should be enough.

**Comment by dai-shi** [comment]
I added a test in #77.

Yeah, I guess you are right.

> ```js
>     CHANGED_PROPERTY]: true, // THIS NEVER HAPPENS
> ```

It _happens_, but never be used in that case.

**Comment by dai-shi** [comment]
https://github.com/dai-shi/proxy-compare/pull/77/commits/f09741d37f19a4d46599f36706beabe1de54ba0d fixed.

**Comment by dai-shi** [comment]
> In addition, we can get also remove `changed === null` as it's **unreachable**,

Now, looking into it.

**Comment by dai-shi** [comment]
Yeah, it should be unreachable because `used` should have at least one property.

https://github.com/dai-shi/proxy-compare/pull/77/commits/42bb1feeb8b580d3f4840510347286a4cb830c52

**Comment by faceyspacey** [comment]
Glad this worked out.

The main thing I wanted to get rid of was the `finally` clause. Long ago *try/catches[/finally]* weren't optimized by V8, but supposedly they were optimized, but who knows by how much.

My goal has been to get the absolute optimal performance, given proxy-compare's proxy, snapshot and isChanged is called so much in component rendering.

Snapshots have amazing performance. I've flamegraphed this stuff a lot on the Chrome Performance tab, and it's a sight to behold when subsequent snapshots are instant due to structural sharing.  It becomes a very a powerful tool. I consider valtio the true answer to React's context, whose performance is horrible, especially for true apps which are highly animated.

So anyway, that's one less thing to add doubts regarding performance.
